### ISSUE TITLE
`mri_21` is not a valid platform

### ISSUE THREAD

**Issue by dannyvanhoof** [RailsApps/rails_apps_composer#297]
When I create a new rails application, at the end I get the error

```
`mri_21` is not a valid platform. The available options are: [:ruby, :ruby_18,
:ruby_19, :ruby_20, :mri, :mri_18, :mri_19, :mri_20, :rbx, :jruby, :mswin,
:mingw, :mingw_18, :mingw_19, :mingw_20]
```

At first sight, this is due to the inclusion of the gem 'binding_of_caller' in the gemfile, which refers to mri_21? If I create an application without 'better_errors', everything goes fine...

**Comment by terryjray** [comment]
@grantgeorge ... your suggestion worked for me also.
