### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by yehshu** [RailsApps/rails_apps_composer#320]
I created an app using rails composer and haven't made any changes to the code yet. It works on my localhost but when I push it to heroku I get this error. I am very new to this so I could just be doing something wrong. Thanks for your help!

Error:

Running: rake assets:precompile
       rake aborted!
       TypeError: no implicit conversion of nil into String
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/config/initializers/devise.rb:13:in `+'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/config/initializers/devise.rb:13:in`block in <top (required)>'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/devise-3.3.0/lib/devise.rb:292:in `setup'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/config/initializers/devise.rb:3:in`<top (required)>'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in`block in load'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in`load'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in`instrument'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:647:in `load_config_initializer'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:612:in`block (2 levels) in class:Engine'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:611:in `each'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:611:in`block in class:Engine'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in`run'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:44:in`each'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:54:in`run_initializers'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:288:in `initialize!'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/config/environment.rb:5:in`<top (required)>'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in`block in require'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in`require'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:264:in `require_environment!'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:367:in`block in run_tasks_blocks'
       /tmp/build_3fc15f47-db7a-4873-bf5f-94ba503858d6/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.1.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app

README:
option  Build a starter application?
choose  Enter your selection: [rails-devise]
option  Get on the mailing list for Rails Composer news?
choose  Enter your selection: [none]
option  Web server for development?
choose  Enter your selection: [webrick]
option  Web server for production?
choose  Enter your selection: [unicorn]
option  Database used in development?
choose  Enter your selection: [sqlite]
option  Template engine?
choose  Enter your selection: [erb]
option  Test framework?
choose  Enter your selection: [none]
option  Continuous testing?
choose  Enter your selection: []
option  Front-end framework?
choose  Enter your selection: [bootstrap3]
option  Add support for sending email?
choose  Enter your selection: [mandrill]
option  Authentication?
choose  Enter your selection: [devise]
option  Devise modules?
choose  Enter your selection: [default]
option  OmniAuth provider?
choose  Enter your selection: []
option  Authorization?
choose  Enter your selection: [false]
option  Use a form builder gem?
choose  Enter your selection: [simple_form]
option  Add pages?
choose  Enter your selection: [users]
option  Set a locale?
choose  Enter your selection: [none]
option  Install page-view analytics?
choose  Enter your selection: [none]
option  Add a deployment mechanism?
choose  Enter your selection: [heroku]
option  Set a robots.txt file to ban spiders?
choose  Enter your selection: [true]
option  Create a GitHub repository? (y/n)
choose  Enter your selection: []
option  Add gem and file for environment variables?
choose  Enter your selection: [false]
option  Reduce assets logger noise during development?
choose  Enter your selection: [true]
option  Improve error reporting with 'better_errors' during development?
choose  Enter your selection: [true]
option  Use 'pry' as console replacement during development and test?
choose  Enter your selection: [false]
option  Use or create a project-specific rvm gemset?
choose  Enter your selection: [false]

**Comment by arikrak** [comment]
This error happens since line 13 in devise.rb has an error if not configured. If you're not sending mail from Devise::Mailer, you can just comment out line 13.
(cf. https://github.com/RailsApps/rails_apps_composer/issues/313 and  https://github.com/RailsApps/rails-composer/issues/204)
