### ISSUE TITLE
Issue while creating controller like as "rails g controller users"

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [RailsApps/rails_apps_composer#331]
Hii,Please check this issue.When i am trying to run rails g controller users i am getting the following issue.

C:\Site\bootstrap>rails g controller users
C:/Site/bootstrap/config/application.rb:13:in `<module:Bootstrap>': uninitialize
d constant Bootstrap::Rails::Application (NameError)
        from C:/Site/bootstrap/config/application.rb:12:in `<top (required)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.19/lib/rails/comma
nds.rb:24:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.19/lib/rails/comma
nds.rb:24:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'

and following file is my Gemfile

source 'https://rubygems.org'
gem 'rails', '3.2.19'
gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'

gem 'bootstrap-sass', '~> 3.1.1.1'

**Comment by DanielKehoe** [comment]
You've submitted the issue in the wrong repository. This repo is for the gem that generates application templates such as Rails Composer.
