### ISSUE TITLE
Error launching application that uses MAILCHIMP_API_KEY (`fetch': key not found)

### ISSUE THREAD

**Issue by scottmatheina** [RailsApps/rails_apps_composer#334]
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
(erb):17:in `fetch': key not found: "MAILCHIMP_API_KEY" (KeyError)
	from (erb):17:in `<main>'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/application.rb:391:in `secrets'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config/environments/development.rb:33:in `block in <top (required)>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config/environments/development.rb:1:in `<top (required)>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config/environment.rb:5:in `<top (required)>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config.ru:3:in `block in <main>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config.ru:in `new'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/config.ru:in `<main>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/builder.rb:49:in `eval'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/server.rb:208:in `app'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/rack-1.6.1/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/bin/rails:8:in `require'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/bin/rails:8:in `<top (required)>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `load'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/client/command.rb:7:in `call'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/bin/spring:48:in `<top (required)>'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `load'
	from /Users/scottmatheina/.rvm/gems/ruby-2.2.2@rails-prelaunch-signup/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/scottmatheina/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/scottmatheina/RailsProjects/rails-prelaunch-signup/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
[~/RailsProjects/rails-prelaunch-signup] ruby-2.2.2@rails-prelaunch-signup $

**Comment by DanielKehoe** [comment]
You need to set the MAILCHIMP_API_KEY in either your Unix ENV variables or the *config/secrets.yml* file.
