### ISSUE TITLE
Difference with rails-composer

### ISSUE THREAD

**Issue by juanpastas** [RailsApps/rails_apps_composer#339]
Hi,

Can you tell me in brief the difference between rails_apps_composer and rails-composer?

I am making  list of rails starter templates and I am not sure which one to include.

**Comment by DanielKehoe** [comment]
Great to hear of your project. I put together a similar list some time ago:
http://railsapps.github.io/rails-application-templates.html

Rails Composer is an application template that generates a dozen different Rails starter apps. It is open source and actively maintained and popular among developers.

The gem rails_apps_composer is a tool I use for generating the Rails Composer application template. Some other developers also use it to generate their own custom application templates. Rails Composer is a complex script. By using rails_apps_composer, it is easier to maintain Rails Composer.

**Comment by juanpastas** [comment]
Thanks Daniel. I remember seeing that page years ago. I forget about it. It's a great resource.

Drone.bz seems offline.

The little table I wrote is at [awesome-rails fork](https://github.com/juanpastas/awesome-rails/tree/patch-1#generators).
