### ISSUE TITLE
Error using rails-stripe-membership-saas

### ISSUE THREAD

**Issue by SylarRuby** [RailsApps/rails_apps_composer#341]
Maybe this is not compatible with rails 4.2.4 but this is disappointing: I use: git clone `git://github.com/RailsApps/rails-stripe-membership-saas.git`

After that it says to use `rvm`, as im using rbenv, so I installed ruby with rvm: `rvm install 2.2.3`. All is well, then `bundle install`. Running `rails s` the go to localhost, sign_up link does not work! Why? Is not this a starter app?? I get `undefined method plan_class for nil:NilClass` and for the plans link:  `Couldn't find Plan`. Am I missing a step?

**Comment by DanielKehoe** [comment]
This is not a problem with Rails Composer. The proper place to report a problem with the [rails-stripe-membership-saas](https://github.com/RailsApps/rails-stripe-membership-saas/issues) app is the issues for that repo.

See https://github.com/RailsApps/rails-stripe-membership-saas/issues/160
