### ISSUE TITLE
Sh fully echoes commands which error exit

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails_apps_composer#382]
As I recall, sometimes new users of this gem who experience an error are asked to report what's printed on their screen. Yet sometimes that output is insufficiently informative, because it's limited to 42 characters. Then they are asked to repeat their command while including a special flag on the command line. Sometimes they are reluctant to spend time to do so, and they move on, or just give up. This additional difficulty is, I suppose, a source of discouragement to new users.

For the benefit of this gem (and others), a while ago I submitted to Ruby/Rake the following pull request to correct this problem. It is still open—and relatively recently it has gotten some attention:

Pull request to Ruby/Rake: [Sh fully echoes commands which error exit](https://github.com/ruby/rake/pull/147)

Please see what @deivid-rodriguez says at the bottom.

Previously I didn't seek "social" support for this pull request. (I assumed I could argue for it as abstractly good, and deserving of acceptance.) It hasn't been accepted yet; I think that's because it lacks much expression of interest from the (Ruby) community.

If this repository expresses interest in the above pull request, then I suppose it may be accepted.

**Comment by MarkDBlackwell** [comment]
@DanielKehoe Recently, ruby/rake [merged](https://github.com/ruby/rake/pull/147#issuecomment-1212880103) the above pull request. :)

**Comment by DanielKehoe** [comment]
My gosh that took 6 years to merge. A minor but useful improvement. Good work, Mark.
